### ISSUE TITLE
ParseError with int32_t in aligned struct

### ISSUE THREAD

**Issue by handsome-fu** [eliben/pycparser#561] opened 2024-12-19 09:39 UTC
**Reproduce code**

```
#include <stdint.h>
struct a {
  _Alignas(16)
  int32_t b;
};
```
**EDITED:** include fake_libc_include
```
ast = parse_file(filename, use_cpp=True,
            cpp_path='gcc',
            cpp_args=['-E', r'-Iutils/fake_libc_include'])
```

**Error log**
_pycparser.plyparser.ParseError: :4:11: before: b_

This program works fine if replace int64_t with int. So I think data type int64_t is key point of this error.
I have already do some research, find yacc will treat int64_t as 'ID' not 'INT'.
![image](https://github.com/user-attachments/assets/69361cfc-d7ae-4f6c-9ee5-814a47ce1d45)

I realize there maybe something wrong while pycparser init lexer, but I doesn't have any idea where to check next. could you please tell me how to further debug this issue?
It will be great if you could fix this issue directly, yacc and lex looks very complex, can't find any clue.

**Comment by gperciva** [comment] 2024-12-19 17:53
`int32_t` and `int64_t` are not part of the C99 standard.  I think you want to `#include <stdint.h>`, and read the FAQ about fake_libc_includes (which also include POSIX headers).

**Comment by handsome-fu** [comment] 2024-12-20 02:02
Hi @gperciva , thank you for your reply.  Unfortunately, issue still exist after include stdint.h.

I can find ```typedef int int32_t;``` in perprocess text, that means fake header already take effect.

Continue to check yacc state machine, LexToken is ```LexToken(TYPEID,'int32_t',4,6336)``` at this time, then state machine report error again.
![image](https://github.com/user-attachments/assets/b8b8c4ce-1287-4477-be4d-3b0206d0fd92)
Do you have any ideas?

**Comment by eliben** [comment] 2024-12-20 13:39
@handsome-fu I'm going to close this, since it isn't a pycparser problem, it's a usage problem.

please read https://github.com/eliben/pycparser?tab=readme-ov-file#interaction-with-the-c-preprocessor and https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/ carefully, and examples like https://github.com/eliben/pycparser/blob/main/examples/using_gcc_E_libc.py

If you still run into an issue after going through these resources, reopen the issue with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Closed by eliben** 2024-12-20 13:39 UTC

**Comment by handsome-fu** [comment] 2024-12-21 12:39
Hi @eliben , this issue still exist after include fake headers, please check my comment before. I have already update MRE code with fake headers.
A new finding is this ticket seems duplicates https://github.com/eliben/pycparser/issues/472, does this known issue?

**Comment by eliben** [comment] 2024-12-21 14:41
I see, so this isn't about headers and custom types. You are right that this is a duplicate of #472 - I've added a shorter reproducer in that issue and labeled it with `patches-welcome`. There's no need to reopen *this* issue - thanks for reporting.
