### ISSUE TITLE
AssertionError: sorry, but this version only supports 100 named groups

### ISSUE THREAD

**Issue by papachoco** [eliben/pycparser#152] opened 2016-10-18 14:26 UTC
Hello,

This has already been reported .  but it happens w/ cffi

Thanks

Carlos

File "/home/ntiuser-outest/buildout/eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/api.py", line 105, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/home/ntiuser-outest/buildout/eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/api.py", line 119, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/home/ntiuser-outest/buildout/eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 299, in parse
    self._internal_parse(csource)
  File "/home/ntiuser-outest/buildout/eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 304, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/home/ntiuser-outest/buildout/eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 260, in _parse
    ast = _get_parser().parse(csource)
  File "/home/ntiuser-outest/buildout/eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 40, in _get_parser
    _parser_cache = pycparser.CParser()
  File "/home/ntiuser-outest/buildout/eggs/pycparser-2.15-py2.7.egg/pycparser/c_parser.py", line 87, in __init__
    outputdir=taboutputdir)
  File "/home/ntiuser-outest/buildout/eggs/pycparser-2.15-py2.7.egg/pycparser/c_lexer.py", line 66, in build
    self.lexer = lex.lex(object=self, **kwargs)
  File "/home/ntiuser-outest/buildout/eggs/pycparser-2.15-py2.7.egg/pycparser/ply/lex.py", line 911, in lex
    lexobj.readtab(lextab, ldict)
  File "/home/ntiuser-outest/buildout/eggs/pycparser-2.15-py2.7.egg/pycparser/ply/lex.py", line 233, in readtab
    titem.append((re.compile(pat, lextab._lexreflags | re.VERBOSE), _names_to_funcs(func_name, fdict)))
  File "/home/ntiuser-outest/.local/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/home/ntiuser-outest/.local/lib/python2.7/re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/ntiuser-outest/.local/lib/python2.7/sre_compile.py", line 583, in compile
    "sorry, but this version only supports 100 named groups"

**Comment by kirbyfan64** [comment] 2016-10-18 14:29
Duplicate of #151.

**Comment by eliben** [comment] 2016-10-18 16:29
Fixed by 2.16, along with #151

**Closed by eliben** 2016-10-18 16:29 UTC
