### ISSUE TITLE
Parse Error on variable name that is a typedef in an outer scope, when it is declared together with another variable

### ISSUE THREAD

**Issue by csarn** [eliben/pycparser#129] opened 2016-06-17 19:46 UTC
Sorry for the long title, but this is a weird circumstance.
This one parses correctly:
```c
typedef int foo;
void f(){
  int foo;
}
```
Note that "int foo" is declared on its own.

This one gives ParseError: test.c:3:10: before: foo
```c
typedef int foo;
void f(){
  int a, foo;
}
```
Just because there is another variable declared in the same statement.

FYI, I stumbled upon this when trying to parse python's own C source code (3.5.1) with pycparser.
This error happens in floatobject.c.

**Comment by eliben** [comment] 2016-06-19 12:14
This is an interesting one :)

pycparser has some workarounds for common cases of the problem described in http://eli.thegreenplace.net/2011/05/02/the-context-sensitivity-of-cs-grammar-revisited

I guess this one was left out. Contributions welcome to fix it - I'm currently over-swamped with other work

**Comment by csarn** [comment] 2016-06-20 19:34
Could you give any hints on where i might start looking? I'm not too familiar with pycparser's internals, but would like to investigate and hopefully fix this bug.

**Comment by eliben** [comment] 2016-06-20 22:49
Look at the functions the parser parameterizes the lexer with; in particular `type_lookup_func` and the usage of a "scope stack" to handle the case where an identifier is a type in one scope but and ID in another

**Comment by eliben** [comment] 2016-10-12 03:50
Closing this as duplicate of #118

**Closed by eliben** 2016-10-12 03:50 UTC
