### ISSUE TITLE
pycparser 2.18 and pycryptodome 3.4.7 in Gajim 0.16.9

### ISSUE THREAD

**Issue by aidecoe** [eliben/pycparser#229] opened 2017-12-29 21:38 UTC
I have [reported problem with Gajim](https://dev.gajim.org/gajim/gajim/issues/8781) failing to start when switched from pycrypto to pycryptodome, but that appears to be an issue with pycparser or maybe pycryptodome. It has been [reported that pycparser 2.14 works fine](https://bugs.gentoo.org/613896#c1).

```
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
/usr/lib64/python2.7/site-packages/pycparser/c_parser.py:20: RuntimeWarning: parsing methods must have __doc__ for pycparser to work properly
  class CParser(PLYParser):
WARNING: There was a problem loading the table file: KeyError('p_direct_id_declarator_1',)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:513: No documentation string specified in function 'p_translation_unit_or_empty' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:522: No documentation string specified in function 'p_translation_unit_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:529: No documentation string specified in function 'p_translation_unit_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:541: No documentation string specified in function 'p_external_declaration_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:546: No documentation string specified in function 'p_external_declaration_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:551: No documentation string specified in function 'p_external_declaration_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:557: No documentation string specified in function 'p_external_declaration_4' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:562: No documentation string specified in function 'p_pp_directive' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:568: No documentation string specified in function 'p_pppragma_directive' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:580: No documentation string specified in function 'p_function_definition_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:597: No documentation string specified in function 'p_function_definition_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:608: No documentation string specified in function 'p_statement' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:628: No documentation string specified in function 'p_decl_body' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:688: No documentation string specified in function 'p_declaration' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:697: No documentation string specified in function 'p_declaration_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:708: No documentation string specified in function 'p_declaration_specifiers_no_type_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:713: No documentation string specified in function 'p_declaration_specifiers_no_type_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:718: No documentation string specified in function 'p_declaration_specifiers_no_type_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:724: No documentation string specified in function 'p_declaration_specifiers_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:729: No documentation string specified in function 'p_declaration_specifiers_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:734: No documentation string specified in function 'p_declaration_specifiers_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:739: No documentation string specified in function 'p_declaration_specifiers_4' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:744: No documentation string specified in function 'p_declaration_specifiers_5' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:749: No documentation string specified in function 'p_declaration_specifiers_6' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:755: No documentation string specified in function 'p_storage_class_specifier' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:764: No documentation string specified in function 'p_function_specifier' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:769: No documentation string specified in function 'p_type_specifier_no_typeid' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:785: No documentation string specified in function 'p_type_specifier' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:793: No documentation string specified in function 'p_type_qualifier' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:800: No documentation string specified in function 'p_init_declarator_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:809: No documentation string specified in function 'p_init_declarator' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:815: No documentation string specified in function 'p_id_init_declarator_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:821: No documentation string specified in function 'p_id_init_declarator' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:829: No documentation string specified in function 'p_specifier_qualifier_list_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:834: No documentation string specified in function 'p_specifier_qualifier_list_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:839: No documentation string specified in function 'p_specifier_qualifier_list_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:844: No documentation string specified in function 'p_specifier_qualifier_list_4' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:853: No documentation string specified in function 'p_struct_or_union_specifier_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:863: No documentation string specified in function 'p_struct_or_union_specifier_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:872: No documentation string specified in function 'p_struct_or_union_specifier_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:882: No documentation string specified in function 'p_struct_or_union' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:890: No documentation string specified in function 'p_struct_declaration_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:899: No documentation string specified in function 'p_struct_declaration_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:937: No documentation string specified in function 'p_struct_declaration_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:942: No documentation string specified in function 'p_struct_declarator_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:951: No documentation string specified in function 'p_struct_declarator_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:956: No documentation string specified in function 'p_struct_declarator_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:965: No documentation string specified in function 'p_enum_specifier_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:971: No documentation string specified in function 'p_enum_specifier_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:976: No documentation string specified in function 'p_enum_specifier_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:982: No documentation string specified in function 'p_enumerator_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:995: No documentation string specified in function 'p_enumerator' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1011: No documentation string specified in function 'p_declarator' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1123: No documentation string specified in function 'p_pointer' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1153: No documentation string specified in function 'p_type_qualifier_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1159: No documentation string specified in function 'p_parameter_type_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1168: No documentation string specified in function 'p_parameter_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1188: No documentation string specified in function 'p_parameter_declaration_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1200: No documentation string specified in function 'p_parameter_declaration_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1231: No documentation string specified in function 'p_identifier_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1241: No documentation string specified in function 'p_initializer_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1246: No documentation string specified in function 'p_initializer_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1255: No documentation string specified in function 'p_initializer_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1267: No documentation string specified in function 'p_designation' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1275: No documentation string specified in function 'p_designator_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1281: No documentation string specified in function 'p_designator' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1287: No documentation string specified in function 'p_type_name' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1298: No documentation string specified in function 'p_abstract_declarator_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1306: No documentation string specified in function 'p_abstract_declarator_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1311: No documentation string specified in function 'p_abstract_declarator_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1321: No documentation string specified in function 'p_direct_abstract_declarator_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1325: No documentation string specified in function 'p_direct_abstract_declarator_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1336: No documentation string specified in function 'p_direct_abstract_declarator_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1345: No documentation string specified in function 'p_direct_abstract_declarator_4' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1356: No documentation string specified in function 'p_direct_abstract_declarator_5' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1365: No documentation string specified in function 'p_direct_abstract_declarator_6' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1375: No documentation string specified in function 'p_direct_abstract_declarator_7' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1386: No documentation string specified in function 'p_block_item' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1394: No documentation string specified in function 'p_block_item_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1401: No documentation string specified in function 'p_compound_statement_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1407: No documentation string specified in function 'p_labeled_statement_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1411: No documentation string specified in function 'p_labeled_statement_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1415: No documentation string specified in function 'p_labeled_statement_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1419: No documentation string specified in function 'p_selection_statement_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1423: No documentation string specified in function 'p_selection_statement_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1427: No documentation string specified in function 'p_selection_statement_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1432: No documentation string specified in function 'p_iteration_statement_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1436: No documentation string specified in function 'p_iteration_statement_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1440: No documentation string specified in function 'p_iteration_statement_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1444: No documentation string specified in function 'p_iteration_statement_4' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1449: No documentation string specified in function 'p_jump_statement_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1453: No documentation string specified in function 'p_jump_statement_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1457: No documentation string specified in function 'p_jump_statement_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1461: No documentation string specified in function 'p_jump_statement_4' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1467: No documentation string specified in function 'p_expression_statement' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1474: No documentation string specified in function 'p_expression' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1487: No documentation string specified in function 'p_typedef_name' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1491: No documentation string specified in function 'p_assignment_expression' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1505: No documentation string specified in function 'p_assignment_operator' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1520: No documentation string specified in function 'p_constant_expression' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1524: No documentation string specified in function 'p_conditional_expression' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1533: No documentation string specified in function 'p_binary_expression' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1559: No documentation string specified in function 'p_cast_expression_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1563: No documentation string specified in function 'p_cast_expression_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1567: No documentation string specified in function 'p_unary_expression_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1571: No documentation string specified in function 'p_unary_expression_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1578: No documentation string specified in function 'p_unary_expression_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1587: No documentation string specified in function 'p_unary_operator' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1597: No documentation string specified in function 'p_postfix_expression_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1601: No documentation string specified in function 'p_postfix_expression_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1605: No documentation string specified in function 'p_postfix_expression_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1611: No documentation string specified in function 'p_postfix_expression_4' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1620: No documentation string specified in function 'p_postfix_expression_5' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1626: No documentation string specified in function 'p_postfix_expression_6' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1632: No documentation string specified in function 'p_primary_expression_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1636: No documentation string specified in function 'p_primary_expression_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1640: No documentation string specified in function 'p_primary_expression_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1646: No documentation string specified in function 'p_primary_expression_4' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1650: No documentation string specified in function 'p_primary_expression_5' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1658: No documentation string specified in function 'p_offsetof_member_designator' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1673: No documentation string specified in function 'p_argument_expression_list' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1683: No documentation string specified in function 'p_identifier' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1687: No documentation string specified in function 'p_constant_1' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1696: No documentation string specified in function 'p_constant_2' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1703: No documentation string specified in function 'p_constant_3' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1715: No documentation string specified in function 'p_unified_string_literal' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1726: No documentation string specified in function 'p_unified_wstring_literal' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1737: No documentation string specified in function 'p_brace_open' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1743: No documentation string specified in function 'p_brace_close' (ignored)
WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1749: No documentation string specified in function 'p_empty' (ignored)
ERROR: start symbol translation_unit_or_empty undefined
```

**Comment by eliben** [comment] 2017-12-31 12:46
Dupe of #198

**Closed by eliben** 2017-12-31 12:46 UTC
