### ISSUE TITLE
ParseError: Objectffly\SerDb.i:43:18: before: __loff_t

### ISSUE THREAD

**Issue by davidaharon** [eliben/pycparser#239] opened 2018-03-06 08:58 UTC
Hi I am getting the following error print:

Traceback (most recent call last):
  File "C:\Work\RE\Tools\VarsExporter\BuildExportedDb.py", line 1076, in <module>
    main()
  File "C:\Work\RE\Tools\VarsExporter\BuildExportedDb.py", line 1032, in main
    ast = parse_file(i_file)
  File "C:\Python27\lib\site-packages\pycparser\__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "C:\Python27\lib\site-packages\pycparser\c_parser.py", line 152, in parse
    debug=debuglevel)
  File "C:\Python27\lib\site-packages\pycparser\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Python27\lib\site-packages\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\Python27\lib\site-packages\pycparser\ply\yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "C:\Python27\lib\site-packages\pycparser\c_parser.py", line 1761, in p_error
    column=self.clex.find_tok_column(p)))
  File "C:\Python27\lib\site-packages\pycparser\plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
ParseError: Objectffly\SerDb.i:43:18: before: __loff_t

What causes the above issue? How Can I handle it?
Maybe preprocess the .i file?

**Comment by eliben** [comment] 2018-03-06 13:08
This is probably a duplicate of #238 -- one issue is sufficient, let's discuss there

**Closed by eliben** 2018-03-06 13:08 UTC
