### ISSUE TITLE
2.20: pytest warnings

### ISSUE THREAD

**Issue by kloczek** [eliben/pycparser#419] opened 2021-06-07 06:52 UTC
```console
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
Using --randomly-seed=3019479507
rootdir: /home/tkloczko/rpmbuild/BUILD/pycparser-release_v2.20
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, cases-3.4.6, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, Faker-8.4.0, cov-2.12.1, randomly-3.8.0, pyfakefs-4.5.0, hypothesis-6.13.14
collected 115 items

tests/test_general.py ....                                                                                                                                           [  3%]
tests/test_c_generator.py ..................................                                                                                                         [ 33%]
tests/test_c_parser.py .................................................                                                                                             [ 76%]
tests/test_c_ast.py ...                                                                                                                                              [ 78%]
. .                                                                                                                                                                  [ 79%]
tests/test_c_ast.py ...                                                                                                                                              [ 82%]
tests/test_c_lexer.py ....................                                                                                                                           [100%]

============================================================================= warnings summary =============================================================================
tests/test_c_lexer.py:170
  /home/tkloczko/rpmbuild/BUILD/pycparser-release_v2.20/tests/test_c_lexer.py:170: DeprecationWarning: invalid escape sequence \9
    '"jx\9"',

tests/test_c_lexer.py:173
  /home/tkloczko/rpmbuild/BUILD/pycparser-release_v2.20/tests/test_c_lexer.py:173: DeprecationWarning: invalid escape sequence \9
    '"fo\9999999"',

-- Docs: https://docs.pytest.org/en/stable/warnings.html
===================================================================== 114 passed, 2 warnings in 13.62s =====================================================================
```

**Comment by eliben** [comment] 2021-06-24 13:07
PRs to fix this welcome

**Comment by hugovk** [comment] 2021-09-23 19:05
Duplicate of https://github.com/eliben/pycparser/issues/349, fixed in https://github.com/eliben/pycparser/pull/389.

**Comment by kloczek** [comment] 2021-09-23 21:10
Looks like there are other fixes already acummulated on top of laste tagged version.
Any chance to make new release?

**Comment by eliben** [comment] 2021-10-04 17:08
Closing this based on https://github.com/eliben/pycparser/issues/419#issuecomment-926078442

Please reopen if this issue still exists for you.

@kloczek see #438 for tracking that

**Closed by eliben** 2021-10-04 17:08 UTC
Labels: patches-welcome
