### ISSUE TITLE
version 2.11 incompatible with cryptography 0.8.2

### ISSUE THREAD

**Issue by jeremycarroll** [eliben/pycparser#75] opened 2015-04-21 22:57 UTC
Our build started failing just after the release, here are the relevant lines from the log:
> 14:49:17 Collecting cryptography>=0.7 (from pyOpenSSL->pysaml2==2.4.0->-r requirements.txt (line 32))
> 14:49:17   Using cached cryptography-0.8.2.tar.gz

> 14:49:18 Collecting pycparser (from cffi>=0.8->cryptography>=0.7->pyOpenSSL->pysaml2==2.4.0->-r requirements.txt (line 32))
> 14:49:18   Downloading pycparser-2.11.tar.gz (297kB)

> 14:49:43   Running setup.py install for cryptography
> 14:49:43     Complete output from command /mnt_ram/jenkins_jobs/Apps-deploy/jenkins-Apps-deploy-810/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-dNQhaD/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tfy0go-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt_ram/jenkins_jobs/Apps-deploy/jenkins-Apps-deploy-810/include/site/python2.7/cryptography:
> 14:49:43     running install
> 14:49:43     Traceback (most recent call last):
> 14:49:43       File "<string>", line 1, in <module>
> 14:49:43       File "/tmp/pip-build-dNQhaD/cryptography/setup.py", line 342, in <module>
> 14:49:43         **keywords_with_side_effects(sys.argv)
> 14:49:43       File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
> 14:49:43         dist.run_commands()
> 14:49:43       File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
> 14:49:43         self.run_command(cmd)
> 14:49:43       File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
> 14:49:43         cmd_obj.ensure_finalized()
> 14:49:43       File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
> 14:49:43         self.finalize_options()
> 14:49:43       File "/tmp/pip-build-dNQhaD/cryptography/setup.py", line 119, in finalize_options
> 14:49:43         self.distribution.ext_modules = get_ext_modules()
> 14:49:43       File "/tmp/pip-build-dNQhaD/cryptography/setup.py", line 78, in get_ext_modules
> 14:49:43         from cryptography.hazmat.bindings.commoncrypto.binding import (
> 14:49:43       File "/tmp/pip-build-dNQhaD/cryptography/src/cryptography/hazmat/bindings/commoncrypto/binding.py", line 14, in <module>
> 14:49:43         class Binding(object):
> 14:49:43       File "/tmp/pip-build-dNQhaD/cryptography/src/cryptography/hazmat/bindings/commoncrypto/binding.py", line 36, in Binding
> 14:49:43         "-framework", "Security", "-framework", "CoreFoundation"
> 14:49:43       File "/tmp/pip-build-dNQhaD/cryptography/src/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
> 14:49:43         extra_link_args=extra_link_args,
> 14:49:43       File "/tmp/pip-build-dNQhaD/cryptography/src/cryptography/hazmat/bindings/utils.py", line 106, in build_ffi
> 14:49:43         ffi.cdef(cdef_source)
> 14:49:43       File "/mnt_ram/jenkins_jobs/Apps-deploy/jenkins-Apps-deploy-810/local/lib/python2.7/site-packages/cffi/api.py", line 106, in cdef
> 14:49:43         self._parser.parse(csource, override=override, packed=packed)
> 14:49:43       File "/mnt_ram/jenkins_jobs/Apps-deploy/jenkins-Apps-deploy-810/local/lib/python2.7/site-packages/cffi/cparser.py", line 165, in parse
> 14:49:43         self._internal_parse(csource)
> 14:49:43       File "/mnt_ram/jenkins_jobs/Apps-deploy/jenkins-Apps-deploy-810/local/lib/python2.7/site-packages/cffi/cparser.py", line 199, in _internal_parse
> 14:49:43         realtype = self._get_type(decl.type, name=decl.name)
> 14:49:43       File "/mnt_ram/jenkins_jobs/Apps-deploy/jenkins-Apps-deploy-810/local/lib/python2.7/site-packages/cffi/cparser.py", line 360, in _get_type
> 14:49:43         return self._get_struct_union_enum_type('struct', type, name)
> 14:49:43       File "/mnt_ram/jenkins_jobs/Apps-deploy/jenkins-Apps-deploy-810/local/lib/python2.7/site-packages/cffi/cparser.py", line 434, in _get_struct_union_enum_type
> 14:49:43         return self._structnode2type[type]
> 14:49:43       File "/usr/lib/python2.7/weakref.py", line 315, in __getitem__
> 14:49:43         return self.data[ref(key)]
> 14:49:43     TypeError: cannot create weak reference to 'Struct' object

**Comment by jeremycarroll** [comment] 2015-04-21 23:45
I believe that [issue 76](https://github.com/eliben/pycparser/issues/76) is the same issue.

**Comment by eliben** [comment] 2015-04-22 00:06
Duplicate of #76, which has been fixed

**Closed by eliben** 2015-04-22 00:06 UTC
